export const RESTAURANT_INFO = {
  name: "Délices d'Africana",
  tagline: "Le plaisir de bien manger",
  address: "Lambanyi, Route d'Enco 5, Conakry, Guinea",
  phone: "+224 621 56 76 76",
  whatsapp: "+224621567676",
  email: "contact@delicesdafricana.com",
  facebook: "https://facebook.com/delicesdafricana",
  hours: {
    days: "Tous les jours",
    open: "09:00",
    close: "23:00",
    display: "09:00 AM - 11:00 PM",
  },
};

export const MENU_CATEGORIES = [
  { id: "all", label: "Tout le Menu", labelEn: "All" },
  { id: "starters", label: "Entrées", labelEn: "Starters" },
  { id: "mains", label: "Plats Principaux", labelEn: "Main Dishes" },
  { id: "desserts", label: "Desserts", labelEn: "Desserts" },
  { id: "drinks", label: "Boissons", labelEn: "Drinks" },
];

export const MENU_ITEMS = [
  // Starters
  {
    id: 1,
    name: "Salade Africaine",
    nameEn: "African Salad",
    description: "Salade fraîche aux saveurs africaines avec vinaigrette maison",
    price: 35000,
    category: "starters",
    image: "https://dctqvomciirmjrkyrihe.supabase.co/storage/v1/object/public/african%20salade/images%20(1).jpg"
    available: true,
    featured: true,
  },
  {
    id: 2,
    name: "Chicken Wings",
    nameEn: "Chicken Wings",
    description: "Ailes de poulet croustillantes marinées aux épices africaines",
    price: 30000,
    category: "starters",
    image: "https://dctqvomciirmjrkyrihe.supabase.co/storage/v1/object/public/resto%20photos%20delice/images.jpg",
    available: true,
    featured: false,
  },
  {
    id: 3,
    name: "Spring Rolls",
    nameEn: "Spring Rolls",
    description: "Rouleaux de printemps croustillants farcis de légumes frais",
    price: 10000,
    category: "starters",
    image: "https://images.pexels.com/photos/37492317/pexels-photo-37492317.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=400&w=600",
    available: true,
    featured: false,
  },
  // Main Dishes
  {
    id: 4,
    name: "Riz Sauce Feuilles",
    nameEn: "Rice with Leaf Sauce",
    description: "Riz blanc servi avec une sauce aux feuilles de manioc traditionnelle",
    price: 80000,
    category: "mains",
    image: "https://images.pexels.com/photos/8166269/pexels-photo-8166269.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=400&w=600",
    available: true,
    featured: true,
  },
  {
    id: 5,
    name: "Riz Sauce Graine",
    nameEn: "Rice with Palm Nut Sauce",
    description: "Riz traditionnel servi avec notre sauce graine aux épices de Guinée",
    price: 90000,
    category: "mains",
    image: "https://images.pexels.com/photos/16627892/pexels-photo-16627892.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=400&w=600",
    available: true,
    featured: true,
  },
  {
    id: 6,
    name: "Fonio Sauce Arachide",
    nameEn: "Fonio with Peanut Sauce",
    description: "Fonio ancestral guinéen servi avec une riche sauce arachide",
    price: 85000,
    category: "mains",
    image: "https://images.pexels.com/photos/18805640/pexels-photo-18805640.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=400&w=600",
    available: true,
    featured: true,
  },
  {
    id: 7,
    name: "Riz au Gras",
    nameEn: "Rice au Gras",
    description: "Riz gras préparé avec viande et légumes frais de saison",
    price: 75000,
    category: "mains",
    image: "https://images.pexels.com/photos/26587862/pexels-photo-26587862.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=400&w=600",
    available: true,
    featured: false,
  },
  {
    id: 8,
    name: "Poulet Braisé",
    nameEn: "Grilled Chicken",
    description: "Poulet entier braisé mariné 24h aux herbes et épices africaines",
    price: 95000,
    category: "mains",
    image: "https://images.pexels.com/photos/37923425/pexels-photo-37923425.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=400&w=600",
    available: true,
    featured: true,
  },
  {
    id: 9,
    name: "Poisson Grillé",
    nameEn: "Grilled Fish",
    description: "Poisson frais grillé à la perfection avec accompagnements maison",
    price: 110000,
    category: "mains",
    image: "https://images.pexels.com/photos/20067063/pexels-photo-20067063.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=400&w=600",
    available: true,
    featured: true,
  },
  {
    id: 10,
    name: "Jollof Rice Special",
    nameEn: "Special Jollof Rice",
    description: "Notre célèbre jollof rice préparé selon la recette secrète de la maison",
    price: 90000,
    category: "mains",
    image: "https://images.pexels.com/photos/34104580/pexels-photo-34104580.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=400&w=600",
    available: true,
    featured: true,
  },
  // Desserts
  {
    id: 11,
    name: "Ice Cream Deluxe",
    nameEn: "Deluxe Ice Cream",
    description: "Glace artisanale aux saveurs tropicales africaines",
    price: 35000,
    category: "desserts",
    image: "https://images.pexels.com/photos/35336025/pexels-photo-35336025.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=400&w=600",
    available: true,
    featured: false,
  },
  {
    id: 12,
    name: "Chocolate Cake",
    nameEn: "Chocolate Cake",
    description: "Gâteau au chocolat fondant garni de ganache et fruits frais",
    price: 45000,
    category: "desserts",
    image: "https://images.pexels.com/photos/26690289/pexels-photo-26690289.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=400&w=600",
    available: true,
    featured: false,
  },
  {
    id: 13,
    name: "African Fruit Salad",
    nameEn: "African Fruit Salad",
    description: "Salade de fruits tropicaux frais de saison avec sirop de canne",
    price: 40000,
    category: "desserts",
    image: "https://images.pexels.com/photos/24742604/pexels-photo-24742604.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=400&w=600",
    available: true,
    featured: false,
  },
  // Drinks
  {
    id: 14,
    name: "Fresh Mango Juice",
    nameEn: "Fresh Mango Juice",
    description: "Jus de mangue fraîchement pressé sans additifs",
    price: 20000,
    category: "drinks",
    image: "https://images.pexels.com/photos/37492317/pexels-photo-37492317.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=400&w=600",
    available: true,
    featured: true,
  },
  {
    id: 15,
    name: "Fresh Pineapple Juice",
    nameEn: "Fresh Pineapple Juice",
    description: "Jus d'ananas frais pressé naturellement sans sucre ajouté",
    price: 20000,
    category: "drinks",
    image: "https://images.pexels.com/photos/24742604/pexels-photo-24742604.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=400&w=600",
    available: true,
    featured: false,
  },
  {
    id: 16,
    name: "Soft Drinks",
    nameEn: "Soft Drinks",
    description: "Coca-Cola, Fanta, Sprite, Top (Citron, Orange)",
    price: 15000,
    category: "drinks",
    image: "https://images.pexels.com/photos/28736727/pexels-photo-28736727.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=400&w=600",
    available: true,
    featured: false,
  },
  {
    id: 17,
    name: "Coffee",
    nameEn: "Coffee",
    description: "Café arabica d'origine guinéenne fraîchement moulu",
    price: 18000,
    category: "drinks",
    image: "https://images.pexels.com/photos/28736731/pexels-photo-28736731.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=400&w=600",
    available: true,
    featured: false,
  },
];

export const ROOMS = [
  {
    id: 1,
    name: "Standard Room",
    nameFr: "Chambre Standard",
    description: "Chambre confortable avec tout le nécessaire pour un séjour agréable",
    price: 450000,
    features: ["Wi-Fi gratuit", "Climatisation", "TV écran plat", "Salle de bain privée", "Petit-déjeuner inclus"],
    image: "https://images.pexels.com/photos/6394651/pexels-photo-6394651.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    capacity: 2,
    size: "25 m²",
  },
  {
    id: 2,
    name: "Deluxe Room",
    nameFr: "Chambre Deluxe",
    description: "Chambre supérieure avec vue et équipements premium pour un séjour inoubliable",
    price: 650000,
    features: ["Wi-Fi haut débit", "Climatisation", "TV Smart 4K", "Mini-bar", "Coffre-fort", "Vue panoramique"],
    image: "https://images.pexels.com/photos/30554296/pexels-photo-30554296.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    capacity: 2,
    size: "35 m²",
  },
  {
    id: 3,
    name: "Executive Suite",
    nameFr: "Suite Exécutive",
    description: "Suite luxueuse avec salon séparé, décoration africaine haut de gamme et services exclusifs",
    price: 1000000,
    features: ["Wi-Fi premium", "Salon privé", "Bain jacuzzi", "Service en chambre 24h/24", "Accueil VIP", "Petit-déjeuner gourmet"],
    image: "https://images.pexels.com/photos/14036272/pexels-photo-14036272.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    capacity: 4,
    size: "60 m²",
  },
];

export const CATERING_SERVICES = [
  {
    id: 1,
    title: "Mariage",
    description: "Faites de votre jour spécial un moment inoubliable avec notre service traiteur premium",
    icon: "Heart",
    image: "https://images.pexels.com/photos/36766850/pexels-photo-36766850.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: 2,
    title: "Événements Corporatifs",
    description: "Solutions traiteur professionnelles pour réunions d'affaires et événements d'entreprise",
    icon: "Briefcase",
    image: "https://images.pexels.com/photos/17001777/pexels-photo-17001777.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: 3,
    title: "Anniversaires",
    description: "Célébrez vos moments de joie avec des saveurs africaines authentiques",
    icon: "Cake",
    image: "https://images.pexels.com/photos/26690289/pexels-photo-26690289.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: 4,
    title: "Événements Religieux",
    description: "Service traiteur respectueux pour baptêmes, mariages religieux et autres cérémonies",
    icon: "Star",
    image: "https://images.pexels.com/photos/28736731/pexels-photo-28736731.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: 5,
    title: "Réceptions Privées",
    description: "Organisation complète de vos réceptions privées avec service personnalisé",
    icon: "Users",
    image: "https://images.pexels.com/photos/17001844/pexels-photo-17001844.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
];

export const TESTIMONIALS = [
  {
    id: 1,
    name: "Mariama Diallo",
    role: "Cliente Fidèle",
    content: "Les meilleures saveurs guinéennes de Conakry ! Le Riz Sauce Graine est exactement comme ma grand-mère le préparait. Service impeccable et cadre magnifique.",
    rating: 5,
    avatar: "MD",
  },
  {
    id: 2,
    name: "Ibrahim Camara",
    role: "Homme d'Affaires",
    content: "Délices d'Africana est devenu mon restaurant préféré pour les déjeuners d'affaires. La cuisine est excellente et l'ambiance est parfaite pour recevoir des clients.",
    rating: 5,
    avatar: "IC",
  },
  {
    id: 3,
    name: "Fatoumata Kouyaté",
    role: "Blogueuse Culinaire",
    content: "Un voyage culinaire authentique à travers les saveurs de la Guinée. Le Fonio Sauce Arachide est une découverte ! Je recommande vivement cet endroit.",
    rating: 5,
    avatar: "FK",
  },
  {
    id: 4,
    name: "Sekou Barry",
    role: "Chef Cuisinier",
    content: "En tant que professionnel de la restauration, je suis impressionné par la qualité et l'authenticité des plats. Les techniques sont maîtrisées et les produits sont frais.",
    rating: 5,
    avatar: "SB",
  },
];
